{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "15149a4c-8644-4bd5-a4f3-61de6ff652b6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "── Validando implementación de referencia ──\n",
      "\n",
      "======================================================================\n",
      "  RESULTADOS: 20/20 trials correctos\n",
      "======================================================================\n",
      "  ✓ Trial 01 | 243 filas | 3 feats | target='label' | pos=57% | OK\n",
      "  ✓ Trial 02 | 231 filas | 6 feats | target='target' | pos=37% | OK\n",
      "  ✓ Trial 03 | 258 filas | 6 feats | target='target' | pos=55% | OK\n",
      "  ✓ Trial 04 | 217 filas | 3 feats | target='fraude' | pos=23% | OK\n",
      "  ✓ Trial 05 | 139 filas | 3 feats | target='fraude' | pos=55% | OK\n",
      "  ✓ Trial 06 | 254 filas | 8 feats | target='fraude' | pos=30% | OK\n",
      "  ✓ Trial 07 | 148 filas | 3 feats | target='label' | pos=56% | OK\n",
      "  ✓ Trial 08 | 189 filas | 7 feats | target='target' | pos=57% | OK\n",
      "  ✓ Trial 09 | 178 filas | 6 feats | target='target' | pos=56% | OK\n",
      "  ✓ Trial 10 | 147 filas | 7 feats | target='label' | pos=65% | OK\n",
      "  ✓ Trial 11 | 286 filas | 5 feats | target='churn' | pos=11% | OK\n",
      "  ✓ Trial 12 | 220 filas | 4 feats | target='label' | pos=51% | OK\n",
      "  ✓ Trial 13 | 143 filas | 4 feats | target='label' | pos=24% | OK\n",
      "  ✓ Trial 14 | 211 filas | 4 feats | target='label' | pos=44% | OK\n",
      "  ✓ Trial 15 | 199 filas | 8 feats | target='label' | pos=4% | OK\n",
      "  ✓ Trial 16 | 198 filas | 4 feats | target='target' | pos=41% | OK\n",
      "  ✓ Trial 17 | 177 filas | 3 feats | target='fraude' | pos=51% | OK\n",
      "  ✓ Trial 18 | 218 filas | 3 feats | target='target' | pos=49% | OK\n",
      "  ✓ Trial 19 | 140 filas | 6 feats | target='fraude' | pos=49% | OK\n",
      "  ✓ Trial 20 | 160 filas | 3 feats | target='target' | pos=4% | OK\n",
      "======================================================================\n",
      "\n",
      "=== INPUT ===\n",
      "target_col : 'churn'\n",
      "Shape      : (140, 8)\n",
      "Features   : ['frecuencia_login', 'score_credito', 'monto_promedio', 'num_productos', 'ingreso', 'num_transacciones', 'edad']\n",
      "Positivos  : 47.1%\n",
      "   frecuencia_login  score_credito  monto_promedio  num_productos  ingreso  num_transacciones    edad  churn\n",
      "0           -0.9065         1.4666          1.2250        -2.2108   2.0513             1.2108 -0.3947      1\n",
      "1            0.0884         0.3231         -0.0297         0.1418   0.2829             1.4414 -0.0251      1\n",
      "2            0.1280         0.2595         -1.8648         0.7436  -0.3317             0.0797 -1.0649      0\n",
      "3            1.2416        -1.6910         -0.2528         0.1361  -2.3532             0.3505  0.9024      0\n",
      "4           -0.7160         0.3374         -0.7128        -0.3168  -0.0452            -0.3815 -2.1895      1\n",
      "5            0.7315         0.4207         -1.5089         0.7681  -0.4862            -0.9728  1.4514      0\n",
      "\n",
      "=== OUTPUT ESPERADO (dict) ===\n",
      "  ingreso                   +0.422857  ████████████████████████████████████████████████████████████████████████████████████\n",
      "  score_credito             +0.051429  ██████████\n",
      "  frecuencia_login          +0.000000  \n",
      "  monto_promedio            +0.000000  \n",
      "  num_productos             +0.000000  \n",
      "  num_transacciones         +0.000000  \n",
      "  edad                      +0.000000  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.inspection import permutation_importance\n",
    "import random\n",
    "\n",
    "\n",
    "# ── Implementación de referencia (ground truth) ───────────────────────────────\n",
    "\n",
    "def _reference_calcular_importancia_permutacion(df, target_col):\n",
    "    X = df.drop(columns=[target_col])\n",
    "    y = df[target_col]\n",
    "\n",
    "    model = RandomForestClassifier(random_state=42)\n",
    "    model.fit(X, y)\n",
    "\n",
    "    result = permutation_importance(model, X, y, random_state=42)\n",
    "\n",
    "    return {col: imp for col, imp in zip(X.columns, result.importances_mean)}\n",
    "\n",
    "\n",
    "# ── Generador principal ───────────────────────────────────────────────────────\n",
    "\n",
    "def generar_caso_de_uso_calcular_importancia_permutacion():\n",
    "    \"\"\"\n",
    "    Genera un caso de uso aleatorio para calcular_importancia_permutacion.\n",
    "\n",
    "    Variaciones cubiertas:\n",
    "    - n_rows          : 80 – 300 filas (mínimo razonable para RF + permutation).\n",
    "    - n_features      : 3 – 8 columnas numéricas.\n",
    "    - nombres_cols    : subconjunto aleatorio del pool para evitar siempre\n",
    "                        los mismos nombres.\n",
    "    - señal vs ruido  : entre 1 y 3 features tienen correlación real con el\n",
    "                        target; el resto son ruido puro → importancias varían.\n",
    "    - target_col_name : aleatorio entre 'target', 'label', 'fraude', 'churn',\n",
    "                        para verificar que la función usa el argumento y no\n",
    "                        asume un nombre fijo.\n",
    "    - Caso edge balanceo: con prob. 0.3 el target está desbalanceado (85/15).\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    input_dict : dict con claves 'df' y 'target_col'\n",
    "    resultado  : dict {feature_name: importancia_promedio}  (ground truth)\n",
    "    \"\"\"\n",
    "\n",
    "    # ── 1. Parámetros estructurales ───────────────────────────────────────────\n",
    "    n_rows     = random.randint(80, 300)\n",
    "    n_features = random.randint(3, 8)\n",
    "\n",
    "    pool_nombres = [\n",
    "        'edad', 'ingreso', 'score_credito', 'dias_cliente', 'num_transacciones',\n",
    "        'monto_promedio', 'deuda_actual', 'num_productos', 'frecuencia_login',\n",
    "        'dias_ultimo_pago', 'saldo_promedio', 'ratio_uso',\n",
    "    ]\n",
    "    feature_names = random.sample(pool_nombres, n_features)\n",
    "\n",
    "    target_col = random.choice(['target', 'label', 'fraude', 'churn'])\n",
    "\n",
    "    # ── 2. Generar features con señal real en 1-3 de ellas ───────────────────\n",
    "    n_signal = random.randint(1, min(3, n_features))\n",
    "    signal_cols = random.sample(feature_names, n_signal)\n",
    "\n",
    "    data = {}\n",
    "    latent = np.random.randn(n_rows)          # variable latente compartida\n",
    "\n",
    "    for col in feature_names:\n",
    "        noise = np.random.randn(n_rows)\n",
    "        if col in signal_cols:\n",
    "            strength = random.uniform(0.6, 1.5)\n",
    "            data[col] = np.round(latent * strength + noise * 0.3, 4)\n",
    "        else:\n",
    "            data[col] = np.round(noise, 4)\n",
    "\n",
    "    # ── 3. Generar target binario ─────────────────────────────────────────────\n",
    "    if random.random() < 0.3:                 # caso edge: desbalanceado\n",
    "        pos_rate = random.uniform(0.10, 0.20)\n",
    "    else:\n",
    "        pos_rate = random.uniform(0.35, 0.65)\n",
    "\n",
    "    signal_sum = sum(data[c] for c in signal_cols)\n",
    "    prob = 1 / (1 + np.exp(-signal_sum))      # sigmoid sobre señal combinada\n",
    "    target_vals = (prob > (1 - pos_rate)).astype(int)\n",
    "\n",
    "    # Garantizar al menos 5 ejemplos de cada clase para que RF funcione bien\n",
    "    if target_vals.sum() < 5:\n",
    "        idx = np.random.choice(np.where(target_vals == 0)[0], 5, replace=False)\n",
    "        target_vals[idx] = 1\n",
    "    if (1 - target_vals).sum() < 5:\n",
    "        idx = np.random.choice(np.where(target_vals == 1)[0], 5, replace=False)\n",
    "        target_vals[idx] = 0\n",
    "\n",
    "    data[target_col] = target_vals\n",
    "\n",
    "    df = pd.DataFrame(data)\n",
    "\n",
    "    # ── 4. Calcular ground truth ──────────────────────────────────────────────\n",
    "    input_dict = {\n",
    "        'df':         df.copy(),\n",
    "        'target_col': target_col,\n",
    "    }\n",
    "    resultado = _reference_calcular_importancia_permutacion(df.copy(), target_col)\n",
    "\n",
    "    return input_dict, resultado\n",
    "\n",
    "\n",
    "# ── Suite de validación ───────────────────────────────────────────────────────\n",
    "\n",
    "def validar_solucion(func, n_trials=20, seed=None):\n",
    "    \"\"\"\n",
    "    Ejecuta n_trials casos aleatorios contra la función del estudiante.\n",
    "\n",
    "    Verificaciones por trial:\n",
    "    1. Retorna un dict.\n",
    "    2. Las claves son exactamente los nombres de las features (sin target_col).\n",
    "    3. Los valores son numéricos (float).\n",
    "    4. Los valores coinciden con el ground truth (atol=1e-9, mismo random_state).\n",
    "    \"\"\"\n",
    "    if seed is not None:\n",
    "        random.seed(seed)\n",
    "        np.random.seed(seed)\n",
    "\n",
    "    resultados = []\n",
    "    for i in range(n_trials):\n",
    "        entrada, esperado = generar_caso_de_uso_calcular_importancia_permutacion()\n",
    "        df_in      = entrada['df']\n",
    "        target_col = entrada['target_col']\n",
    "        feat_cols  = [c for c in df_in.columns if c != target_col]\n",
    "        pos_rate   = round(df_in[target_col].mean(), 2)\n",
    "\n",
    "        try:\n",
    "            resultado = func(df_in.copy(), target_col)\n",
    "            errores = []\n",
    "\n",
    "            # 1. Es un dict\n",
    "            if not isinstance(resultado, dict):\n",
    "                errores.append(f\"debe retornar dict, recibió {type(resultado)}\")\n",
    "            else:\n",
    "                # 2. Claves correctas\n",
    "                claves_res = set(resultado.keys())\n",
    "                claves_esp = set(feat_cols)\n",
    "                if claves_res != claves_esp:\n",
    "                    sobrantes = claves_res - claves_esp\n",
    "                    faltantes = claves_esp - claves_res\n",
    "                    if sobrantes:\n",
    "                        errores.append(f\"claves sobrantes: {sobrantes}\")\n",
    "                    if faltantes:\n",
    "                        errores.append(f\"claves faltantes: {faltantes}\")\n",
    "\n",
    "                # 3. Valores numéricos\n",
    "                for k, v in resultado.items():\n",
    "                    if not isinstance(v, (int, float, np.floating)):\n",
    "                        errores.append(f\"valor de '{k}' no es numérico: {type(v)}\")\n",
    "                        break\n",
    "\n",
    "                # 4. Coincide con ground truth\n",
    "                if not errores:\n",
    "                    for col in feat_cols:\n",
    "                        v_res = resultado[col]\n",
    "                        v_esp = esperado[col]\n",
    "                        if abs(v_res - v_esp) > 1e-9:\n",
    "                            errores.append(\n",
    "                                f\"'{col}': got={v_res:.6f}, esp={v_esp:.6f} \"\n",
    "                                f\"(diff={abs(v_res-v_esp):.2e})\"\n",
    "                            )\n",
    "\n",
    "            passed = len(errores) == 0\n",
    "            nota   = \"; \".join(errores) if errores else \"OK\"\n",
    "\n",
    "        except Exception as exc:\n",
    "            passed = False\n",
    "            nota   = f\"EXCEPCIÓN: {exc}\"\n",
    "\n",
    "        resultados.append({\n",
    "            'trial':    i + 1,\n",
    "            'n_rows':   len(df_in),\n",
    "            'n_feats':  len(feat_cols),\n",
    "            'target':   target_col,\n",
    "            'pos_rate': pos_rate,\n",
    "            'passed':   passed,\n",
    "            'nota':     nota,\n",
    "        })\n",
    "\n",
    "    # ── Reporte ───────────────────────────────────────────────────────────────\n",
    "    total  = len(resultados)\n",
    "    passed = sum(r['passed'] for r in resultados)\n",
    "    print(f\"\\n{'='*70}\")\n",
    "    print(f\"  RESULTADOS: {passed}/{total} trials correctos\")\n",
    "    print(f\"{'='*70}\")\n",
    "    for r in resultados:\n",
    "        icono = \"✓\" if r['passed'] else \"✗\"\n",
    "        print(\n",
    "            f\"  {icono} Trial {r['trial']:02d} | {r['n_rows']:3d} filas | \"\n",
    "            f\"{r['n_feats']} feats | target='{r['target']}' | \"\n",
    "            f\"pos={r['pos_rate']:.0%} | {r['nota']}\"\n",
    "        )\n",
    "    print(f\"{'='*70}\\n\")\n",
    "    return passed == total\n",
    "\n",
    "\n",
    "# ── Demo ──────────────────────────────────────────────────────────────────────\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"── Validando implementación de referencia ──\")\n",
    "    validar_solucion(_reference_calcular_importancia_permutacion, n_trials=20, seed=42)\n",
    "\n",
    "    # Demo visual\n",
    "    random.seed(3); np.random.seed(3)\n",
    "    entrada, esperado = generar_caso_de_uso_calcular_importancia_permutacion()\n",
    "    df_in      = entrada['df']\n",
    "    target_col = entrada['target_col']\n",
    "    feat_cols  = [c for c in df_in.columns if c != target_col]\n",
    "\n",
    "    print(\"=== INPUT ===\")\n",
    "    print(f\"target_col : '{target_col}'\")\n",
    "    print(f\"Shape      : {df_in.shape}\")\n",
    "    print(f\"Features   : {feat_cols}\")\n",
    "    print(f\"Positivos  : {df_in[target_col].mean():.1%}\")\n",
    "    print(df_in.head(6).to_string())\n",
    "\n",
    "    print(\"\\n=== OUTPUT ESPERADO (dict) ===\")\n",
    "    for k, v in sorted(esperado.items(), key=lambda x: -x[1]):\n",
    "        bar = \"█\" * int(max(0, v) * 200)\n",
    "        print(f\"  {k:<25} {v:+.6f}  {bar}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c4c593c-bf3d-4764-8697-798b1830714e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
