{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5ca1fe28-2a7f-46b3-8e9d-3b3839453116",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "── Validando implementación de referencia ──\n",
      "\n",
      "============================================================\n",
      "  RESULTADOS: 20/20 trials correctos\n",
      "============================================================\n",
      "  ✓ Trial 01 |  92 filas | 3 cols | OK\n",
      "  ✓ Trial 02 | 154 filas | 2 cols | OK\n",
      "  ✓ Trial 03 |  84 filas | 5 cols | OK\n",
      "  ✓ Trial 04 |  30 filas | 6 cols | OK\n",
      "  ✓ Trial 05 | 188 filas | 7 cols | OK\n",
      "  ✓ Trial 06 |  69 filas | 3 cols | OK\n",
      "  ✓ Trial 07 | 186 filas | 8 cols [col_cte] | OK\n",
      "  ✓ Trial 08 | 199 filas | 4 cols | OK\n",
      "  ✓ Trial 09 |  67 filas | 6 cols | OK\n",
      "  ✓ Trial 10 |  96 filas | 3 cols | OK\n",
      "  ✓ Trial 11 |  55 filas | 5 cols [col_cte] | OK\n",
      "  ✓ Trial 12 |  45 filas | 5 cols | OK\n",
      "  ✓ Trial 13 |  14 filas | 8 cols | OK\n",
      "  ✓ Trial 14 | 143 filas | 4 cols | OK\n",
      "  ✓ Trial 15 |  45 filas | 5 cols | OK\n",
      "  ✓ Trial 16 |  26 filas | 2 cols | OK\n",
      "  ✓ Trial 17 | 183 filas | 8 cols | OK\n",
      "  ✓ Trial 18 | 145 filas | 8 cols [col_cte] | OK\n",
      "  ✓ Trial 19 |  24 filas | 2 cols [col_cte] | OK\n",
      "  ✓ Trial 20 | 103 filas | 4 cols | OK\n",
      "============================================================\n",
      "\n",
      "=== INPUT ===\n",
      "Shape   : (44, 6)\n",
      "Columnas: ['ingreso', 'saldo', 'peso', 'dias', 'cantidad', 'deuda']\n",
      "   ingreso     saldo      peso      dias  cantidad     deuda\n",
      "0    355.0  -80.8642  357.4417  318.3801     443.0  300.8245\n",
      "1    266.0 -109.6628  358.0505  339.4334     440.0  248.4702\n",
      "2    270.0  -74.9978  358.0925  342.2980     442.0  298.0925\n",
      "3    248.0    4.9470  357.4799  325.5516     440.0  229.9881\n",
      "4    325.0  -77.9604  357.1413  339.0792     438.0  167.5343\n",
      "5    199.0  -57.1490  356.9821  319.3936     441.0  339.9381\n",
      "\n",
      "=== OUTPUT ESPERADO ===\n",
      "medias       (shape (6,)): [287.0909 -75.4963 357.4066 334.3725 440.6818 224.6902]\n",
      "desviaciones (shape (6,)): [38.8514 35.5698  0.5453 11.2882  2.009  52.8971]\n",
      "\n",
      "Detalle por columna:\n",
      "  ingreso         media= +287.0909   std=38.8514\n",
      "  saldo           media=  -75.4963   std=35.5698\n",
      "  peso            media= +357.4066   std=0.5453\n",
      "  dias            media= +334.3725   std=11.2882\n",
      "  cantidad        media= +440.6818   std=2.0090\n",
      "  deuda           media= +224.6902   std=52.8971\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import random\n",
    "\n",
    "\n",
    "# ── Implementación de referencia (ground truth) ───────────────────────────────\n",
    "\n",
    "def _reference_calcular_estadisticas(df):\n",
    "    medias = df.mean().to_numpy()\n",
    "    desviaciones = df.std().to_numpy()\n",
    "    return medias, desviaciones\n",
    "\n",
    "\n",
    "# ── Generador principal ───────────────────────────────────────────────────────\n",
    "\n",
    "def generar_caso_de_uso_calcular_estadisticas():\n",
    "    \"\"\"\n",
    "    Genera un caso de uso aleatorio para calcular_estadisticas.\n",
    "\n",
    "    Variaciones cubiertas:\n",
    "    - n_rows      : 10 – 200 filas.\n",
    "    - n_cols      : 2 – 8 columnas numéricas.\n",
    "    - nombres     : subconjunto aleatorio del pool para evitar nombres fijos.\n",
    "    - distribución: cada columna tiene media y escala distintas (no centradas\n",
    "                    en 0) para que las medias y stds varíen entre columnas.\n",
    "    - dtypes       : mezcla aleatoria de float64 e int64 (ambos son numéricos).\n",
    "    - Caso edge columna constante: con prob. 0.2 una columna tiene todos los\n",
    "                    valores iguales → std = 0 (prueba que no hay división por 0).\n",
    "\n",
    "    Retorna\n",
    "    -------\n",
    "    input_dict : dict con clave 'df'\n",
    "    (medias, desviaciones) : tupla de numpy arrays (ground truth)\n",
    "    \"\"\"\n",
    "\n",
    "    # ── 1. Parámetros estructurales ───────────────────────────────────────────\n",
    "    n_rows = random.randint(10, 200)\n",
    "    n_cols = random.randint(2, 8)\n",
    "\n",
    "    pool_nombres = [\n",
    "        'edad', 'ingreso', 'score', 'deuda', 'saldo', 'monto',\n",
    "        'frecuencia', 'dias', 'cantidad', 'ratio', 'altura', 'peso',\n",
    "    ]\n",
    "    col_names = random.sample(pool_nombres, n_cols)\n",
    "\n",
    "    # ── 2. Generar datos con medias y escalas variadas ────────────────────────\n",
    "    data = {}\n",
    "    for col in col_names:\n",
    "        media_real = random.uniform(-100, 500)\n",
    "        escala     = random.uniform(0.5, 50)\n",
    "        usar_int   = random.random() < 0.3     # 30% de columnas como int\n",
    "\n",
    "        valores = np.random.randn(n_rows) * escala + media_real\n",
    "        if usar_int:\n",
    "            valores = valores.astype(int).astype(float)  # int → float para consistencia\n",
    "        data[col] = np.round(valores, 4)\n",
    "\n",
    "    df = pd.DataFrame(data)\n",
    "\n",
    "    # ── 3. Caso edge: columna constante (std = 0) ─────────────────────────────\n",
    "    if random.random() < 0.2:\n",
    "        col_constante = random.choice(col_names)\n",
    "        valor_fijo = round(random.uniform(-50, 200), 2)\n",
    "        df[col_constante] = valor_fijo\n",
    "\n",
    "    # ── 4. Calcular ground truth ──────────────────────────────────────────────\n",
    "    input_dict = {'df': df.copy()}\n",
    "    medias, desviaciones = _reference_calcular_estadisticas(df.copy())\n",
    "\n",
    "    return input_dict, (medias, desviaciones)\n",
    "\n",
    "\n",
    "# ── Suite de validación ───────────────────────────────────────────────────────\n",
    "\n",
    "def validar_solucion(func, n_trials=20, seed=None):\n",
    "    \"\"\"\n",
    "    Ejecuta n_trials casos aleatorios contra la función del estudiante.\n",
    "\n",
    "    Verificaciones por trial:\n",
    "    1. Retorna una tupla de longitud 2.\n",
    "    2. Ambos elementos son numpy.ndarray.\n",
    "    3. Ambos arrays tienen shape (n_cols,).\n",
    "    4. Los valores de medias coinciden con el ground truth (atol=1e-9).\n",
    "    5. Los valores de desviaciones coinciden con el ground truth (atol=1e-9).\n",
    "    \"\"\"\n",
    "    if seed is not None:\n",
    "        random.seed(seed)\n",
    "        np.random.seed(seed)\n",
    "\n",
    "    resultados = []\n",
    "    for i in range(n_trials):\n",
    "        entrada, (medias_esp, stds_esp) = generar_caso_de_uso_calcular_estadisticas()\n",
    "        df_in  = entrada['df']\n",
    "        n_cols = df_in.shape[1]\n",
    "        tiene_constante = any(df_in[c].nunique() == 1 for c in df_in.columns)\n",
    "\n",
    "        try:\n",
    "            resultado = func(df_in.copy())\n",
    "            errores = []\n",
    "\n",
    "            # 1. Tupla de 2 elementos\n",
    "            if not (isinstance(resultado, tuple) and len(resultado) == 2):\n",
    "                errores.append(f\"debe retornar tupla de 2, recibió {type(resultado)}\")\n",
    "            else:\n",
    "                medias_res, stds_res = resultado\n",
    "\n",
    "                # 2. Tipos numpy\n",
    "                if not isinstance(medias_res, np.ndarray):\n",
    "                    errores.append(f\"medias debe ser ndarray, es {type(medias_res)}\")\n",
    "                if not isinstance(stds_res, np.ndarray):\n",
    "                    errores.append(f\"desviaciones debe ser ndarray, es {type(stds_res)}\")\n",
    "\n",
    "                if isinstance(medias_res, np.ndarray) and isinstance(stds_res, np.ndarray):\n",
    "\n",
    "                    # 3. Shapes\n",
    "                    if medias_res.shape != (n_cols,):\n",
    "                        errores.append(f\"medias.shape={medias_res.shape}, esperado ({n_cols},)\")\n",
    "                    if stds_res.shape != (n_cols,):\n",
    "                        errores.append(f\"desviaciones.shape={stds_res.shape}, esperado ({n_cols},)\")\n",
    "\n",
    "                    # 4 & 5. Valores correctos\n",
    "                    if not errores:\n",
    "                        if not np.allclose(medias_res, medias_esp, atol=1e-9):\n",
    "                            diff = np.abs(medias_res - medias_esp).max()\n",
    "                            errores.append(f\"medias incorrectas (diff max={diff:.2e})\")\n",
    "                        if not np.allclose(stds_res, stds_esp, atol=1e-9):\n",
    "                            diff = np.abs(stds_res - stds_esp).max()\n",
    "                            errores.append(f\"desviaciones incorrectas (diff max={diff:.2e})\")\n",
    "\n",
    "            passed = len(errores) == 0\n",
    "            nota   = \"; \".join(errores) if errores else \"OK\"\n",
    "\n",
    "        except Exception as exc:\n",
    "            passed = False\n",
    "            nota   = f\"EXCEPCIÓN: {exc}\"\n",
    "\n",
    "        resultados.append({\n",
    "            'trial':     i + 1,\n",
    "            'n_rows':    df_in.shape[0],\n",
    "            'n_cols':    n_cols,\n",
    "            'constante': tiene_constante,\n",
    "            'passed':    passed,\n",
    "            'nota':      nota,\n",
    "        })\n",
    "\n",
    "    # ── Reporte ───────────────────────────────────────────────────────────────\n",
    "    total  = len(resultados)\n",
    "    passed = sum(r['passed'] for r in resultados)\n",
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"  RESULTADOS: {passed}/{total} trials correctos\")\n",
    "    print(f\"{'='*60}\")\n",
    "    for r in resultados:\n",
    "        icono     = \"✓\" if r['passed'] else \"✗\"\n",
    "        constante = \" [col_cte]\" if r['constante'] else \"\"\n",
    "        print(\n",
    "            f\"  {icono} Trial {r['trial']:02d} | {r['n_rows']:3d} filas | \"\n",
    "            f\"{r['n_cols']} cols{constante} | {r['nota']}\"\n",
    "        )\n",
    "    print(f\"{'='*60}\\n\")\n",
    "    return passed == total\n",
    "\n",
    "\n",
    "# ── Demo ──────────────────────────────────────────────────────────────────────\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"── Validando implementación de referencia ──\")\n",
    "    validar_solucion(_reference_calcular_estadisticas, n_trials=20, seed=7)\n",
    "\n",
    "    # Demo visual\n",
    "    random.seed(1); np.random.seed(1)\n",
    "    entrada, (medias, stds) = generar_caso_de_uso_calcular_estadisticas()\n",
    "    df_in = entrada['df']\n",
    "\n",
    "    print(\"=== INPUT ===\")\n",
    "    print(f\"Shape   : {df_in.shape}\")\n",
    "    print(f\"Columnas: {list(df_in.columns)}\")\n",
    "    print(df_in.head(6).to_string())\n",
    "\n",
    "    print(\"\\n=== OUTPUT ESPERADO ===\")\n",
    "    print(f\"medias       (shape {medias.shape}): {np.round(medias, 4)}\")\n",
    "    print(f\"desviaciones (shape {stds.shape}): {np.round(stds, 4)}\")\n",
    "    print(f\"\\nDetalle por columna:\")\n",
    "    for col, m, s in zip(df_in.columns, medias, stds):\n",
    "        print(f\"  {col:<15} media={m:+10.4f}   std={s:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e3674df-aae2-4b00-b7b6-1984a8694d29",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
